{
  imports = [
    ./archiveteam-warrior.nix
    ./backup-receiver.nix
    ./blackbox-prober.nix
    ./fiber7-prober.nix
    ./fifoci-worker.nix
    ./gaming-client.nix
    ./homenet
    ./infra-dev-machine.nix
    ./iot-gateway.nix
    ./irc-client.nix
    ./mastodon-server.nix
    ./matrix-client.nix
    ./matrix-irc-bridge.nix
    ./matrix-signal-bridge.nix
    ./matrix-synatainer.nix
    ./matrix-synapse.nix
    ./monitoring
    ./music-server.nix
    ./nas.nix
    ./nas-client.nix
    ./nix-builder.nix
    ./print-server.nix
    ./publibike-locator.nix
    ./repology-notifier.nix
    ./s3.nix
    ./seedbox.nix
    ./smtp-server.nix
    ./snmp-exporter.nix
    ./syncthing-mirror.nix
    ./syncthing-relay.nix
    ./tor-relay.nix
    ./wireguard-peer.nix
  ];
}
