{
  imports = [
    ./blackbox-prober.nix
    ./fiber7-prober.nix
    ./fifoci-worker.nix
    ./gaming-client.nix
    ./infra-dev-machine.nix
    ./iot-gateway.nix
    ./irc-client.nix
    ./matrix-synapse.nix
    ./music-server.nix
    ./nix-builder.nix
    ./publibike-locator.nix
    ./smtp-server.nix
    ./syncthing-mirror.nix
    ./syncthing-relay.nix
    ./tor-relay.nix
    ./wireguard-peer.nix
  ];
}
