# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, staging, ... }:

{
  imports = [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix> ];

  config = lib.mkIf (!staging) {
    boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
    boot.kernelModules = [ "kvm-intel" ];
    boot.extraModulePackages = [ ];

    boot.loader.systemd-boot.enable = true;

    fileSystems."/" =
      { device = "/dev/disk/by-uuid/9e0a75fd-be40-4b3f-891c-092f4f201725";
        fsType = "ext4";
      };

    boot.initrd.luks.devices."plain".device = "/dev/disk/by-uuid/592d5b09-2910-44be-abe6-dceac543e726";

    fileSystems."/boot" =
      { device = "/dev/disk/by-uuid/E5C0-C972";
        fsType = "vfat";
      };

    nix.maxJobs = lib.mkDefault 4;
    powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";
  };
}
